### ISSUE TITLE
multiple threshold check

### ISSUE THREAD

**Issue by ShilpaSangappa** [ogvalt/MSDNet-keras#1]
Hello,

I was looking at your implementation, which happens to be the only MSDNet implementation in keras :).

The paper MSDNet talks about early exit prediction where each classifier output is checked for a certain threshold. If it meets the threshold criteria the network exits early. 

I am not able to figure out where the thresholds for each classifier are listed and where the conditional exit is happening.

Thanks in advance.

**Comment by ogvalt** [comment]
@ShilpaSangappa 
Sorry, I wasn't planned to support this projects.
Hope you're doing well
