### ISSUE TITLE
one question about train code  model.output_layers

### ISSUE THREAD

**Issue by alexliyang** [ogvalt/MSDNet-keras#2]
I try to use the code to experiment, but  the error is no model.output_layers, when I change output_layers to outputs, then new error is :
 File "train.py", line 91, in <module>
    metrics=['accuracy'])
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\
training.py", line 119, in compile
    str(self.output_names))
ValueError: Unknown entry in loss dictionary: "classifier_8_dense/Sigmoid:0". On
ly expected the following keys: ['classifier_4_dense', 'classifier_6_dense', 'cl
assifier_8_dense', 'classifier_10_dense', 'classifier_12_dense', 'classifier_14_
dense', 'classifier_16_dense', 'classifier_18_dense', 'classifier_20_dense', 'cl
assifier_22_dense', 'classifier_24_dense']

how to correct this error

**Comment by JoJo-ops** [comment]
i have the same problem

**Comment by JoJo-ops** [comment]
is model._output_layers not model.output_layers

**Comment by ogvalt** [comment]
@JoJo-ops @alexliyang Sorry guys, I had no intent to support this project.
Hope you are doing well.
